### PR TITLE
Initial snowplow tracking

### PR DESCRIPTION
**Pull request by ianco**
Signed-off-by: Ian Costanzo <ian@anon-solutions.ca>

Initial snowplow tracking, see:  https://github.com/bcgov/aries-vcr/issues/694

### CODE REVIEW

**Comment by swcurran** [comment]
"Snowplow tracking"? Do tell...

**Review by amanji — COMMENTED** [review]
Do we want to add tracking for V3 and V4 endpoints as well?

**Comment by ianco** [comment]
> Do we want to add tracking for V3 and V4 endpoints as well?

Yes, I've just done one endpoint so far ...

**Comment by WadeBarnes** [comment]
> @WadeBarnes does this look correct to you, based on the spec?
@ianco, Yes.
Would it be possible to wrap the tacking in a middleware component such that the tracking can be done more generically rather than having to discretely implement it on each endpoint?

**Comment by WadeBarnes** [comment]
> "Snowplow tracking"? Do tell...
@swcurran, To add API statistics to the GDX analytics  dashboards.

**Comment by ianco** [comment]
> > Would it be possible to wrap the tacking in a middleware component such that the tracking can be done more generically rather than having to discretely implement it on each endpoint?

@WadeBarnes  that's what I'm looking into next.  I think in general Yes it can be done, but there is some specific request-specific info that is attached to the tracking event, I'm not sure how generically we can "harvest" this info from the request.

**Comment by WadeBarnes** [comment]
@ianco, The `internal_call` attribute was included as a flag to indicate whether the call was coming, "internally", from an OrgBook component such as the frontend during regular use, or a direct API call from and external integrating party.  That way we could differentiate between application and integration usage.  We just need to come up with a way to differentiate that for ourselves.

**Comment by ianco** [comment]
@WadeBarnes  the other things we need to derive dynamically are:

- the `url` (we can get this from the request, but ideally need to map to the url pattern e.g. `issuer/{id}/credentialtype` vs `issuer/1/credentialtype`)
- the `parameters` (possible to parse generically from the request?)
- the `total` (count of items in the result - possible to dynamically parse the response stream?)

... and `internal_call`, as you mention.

My gut feel is that a combination of generic processing/request-specific processing (for some API's) will be required.

**Comment by ianco** [comment]
Some updates @WadeBarnes  @amanji :

- tracking logic moved to middleware
- CORS headers are used to determine if call is internal or not (internal = the orgbook app or swagger UI)
- parameters are derived from GET or POST parameters
- endpoint and item count can be set by the endpoint-specific code (passed to middleware as request attributes)
- if endpoint is not provided, the derived django pattern will be used (could be something like `api/credential/(?P<credential_id>[^/.]+)/verify`, although it may be possible to build some rules to simplify this automatically)
- if count is not provided will use `count = 0`

Only `/api` endpoints are currently tracked

**Comment by ianco** [comment]
- massage the django endpoint url to make it look nice
- add item count to many of the v2/3/4 services

**Comment by WadeBarnes** [comment]
@ianco, Looks good.  I'd recommend squashing your changes into a single commit to clean up the history.

**Review by WadeBarnes — APPROVED** [review]

**Pull request merged**
