### PR TITLE
Restore location of management commands

### PR DESCRIPTION
**Pull request by ianco**
This puts the commands back where django can find them ...

Issue #800

### CODE REVIEW

**Comment by WadeBarnes** [comment]
@ianco, @amanji, Is this going to cause any issues with the refactoring that moved these files in the first place?

**Review by amanji — APPROVED** [review]

**Comment by amanji** [comment]
I don't believe they are being used outside of Django's `manage.py`. The processing flow for incoming credentials in Aries VCR goes through a different function.

**Comment by ianco** [comment]
> @ianco, @amanji, Is this going to cause any issues with the refactoring that moved these files in the first place?

That's a question for @amanji

I tested them once they were moved back and they are now working

**Comment by WadeBarnes** [comment]
> I don't believe they are being used outside of Django's `manage.py`. The processing flow for incoming credentials in Aries VCR goes through a different function.

Does that mean they got moved by mistake, and now they are back where they belong?

**Pull request merged**
