### PR TITLE
`DEBUG` variable should be disabled by default

### PR DESCRIPTION
**Pull request by amanji**
Signed-off-by: Akiff Manji <akiff.manji@gmail.com>

### CODE REVIEW

**Review by ianco — CHANGES_REQUESTED** [review]
Default should be "false"

**Review by esune — APPROVED** [review]

**Review by esune — CHANGES_REQUESTED** [review]
I agree with @ianco, the default running mode should be `DEBUG=false` in order for the Django development server to be used only if explicitly required.

**Comment by ianco** [comment]
`THEME=bcgov ./manage start` works but the swagger page gives me an error when I run `THEME=bcgov DEBUG=false ./manage start`

**Comment by amanji** [comment]
>THEME=bcgov ./manage start works but the swagger page gives me an error when I run THEME=bcgov DEBUG=false ./manage start

This is correct and behaviour that was already established in the repo. We'll need to create another issue to actually fix the build when `DEBUG` is disabled.

**Comment by ianco** [comment]
It's not correct behaviour, this error was introduced in commit `27e4d449ddcbd72c60a8f498a73a597f11db3a15`, I thought this PR was to fix this?

Or did this error exist in the repo prior to this commit?

**Comment by amanji** [comment]
> It's not correct behaviour, this error was introduced in commit `27e4d449ddcbd72c60a8f498a73a597f11db3a15`, I thought this PR was to fix this?
> 
> Or did this error exist in the repo prior to this commit?

The behaviour existed prior to this change but was exposed by re-purposing the `DJANGO_DEBUG` variable (previously linked to `DEBUG`). This PR separates the two variables from each other and re-establishes previous behaviour. I would need to issue an update to resolve the previous issues observed when `DEBUG` is disabled.

**Review by ianco — APPROVED** [review]

**Review by esune — APPROVED** [review]

**Comment by esune** [comment]
@amanji can/should this be merged?

**Comment by amanji** [comment]
If we simply want to re-establish previous behaviour then it can be merged. Otherwise we still need to fix the issue with staticfiles in development mode when debugging is disabled.

**Comment by ianco** [comment]
Let's leave it out (close the PR) - the issue can up because one of the devs (from BuyBC I think) was having issues but we managed to resolve them, no there are no outstanding issues ...

**Comment by esune** [comment]
I can provide an example of how to handle static file serving in both modes if we want to fix it to leave thing clean.
- `settings.py` should have something that looks like this to support serving static files in both scenarios:[link]https://github.com/bcgov/vc-visual-verifier/blob/master/src/vc_visual_verifier/settings.py#L133-L145)
- `urls.py` needs to include the static file setting to serve files during development (it is only used in development and has no effect in production mode): [link](https://github.com/bcgov/vc-visual-verifier/blob/master/src/vc_visual_verifier/urls.py#L26)

**Pull request merged**
