### PR TITLE
feat: W3C credential support

### PR DESCRIPTION
**Pull request by amanji**
This PR adds support for storing W3C credential formats in aries-vcr. A number of db migrations have been added to be able to store the raw JSON data in the db along with Django code and tests to support registering W3C credential issuers and to receive W3C credentials.

### CODE REVIEW

**Comment by ianco** [comment]
@amanji  how are you testing sending a W3C json credential?

**Comment by ianco** [comment]
Testing with the BC Reg issuer I get errors when I try to issue credentials:

```
vcr-agent-1   | 2024-09-03 21:32:52,419 aries_cloudagent.transport.outbound.manager ERROR Outbound message could not be delivered to http://vcr-api:8080/agentcb/topic/issue_credential/
vcr-agent-1   | Traceback (most recent call last):
vcr-agent-1   |   File "/home/indy/.local/lib/python3.9/site-packages/aiohttp/connector.py", line 1025, in _wrap_create_connection
vcr-agent-1   |     return await self._loop.create_connection(*args, **kwargs)
vcr-agent-1   |   File "/usr/local/lib/python3.9/asyncio/base_events.py", line 1065, in create_connection
vcr-agent-1   |     raise exceptions[0]
vcr-agent-1   |   File "/usr/local/lib/python3.9/asyncio/base_events.py", line 1050, in create_connection
vcr-agent-1   |     sock = await self._connect_sock(
vcr-agent-1   |   File "/usr/local/lib/python3.9/asyncio/base_events.py", line 961, in _connect_sock
vcr-agent-1   |     await self.sock_connect(sock, address)
vcr-agent-1   |   File "/usr/local/lib/python3.9/asyncio/selector_events.py", line 500, in sock_connect
vcr-agent-1   |     return await fut
vcr-agent-1   |   File "/usr/local/lib/python3.9/asyncio/futures.py", line 284, in __await__
vcr-agent-1   |     yield self  # This tells Task to wait for completion.
vcr-agent-1   |   File "/usr/local/lib/python3.9/asyncio/tasks.py", line 328, in __wakeup
vcr-agent-1   |     future.result()
vcr-agent-1   |   File "/usr/local/lib/python3.9/asyncio/futures.py", line 201, in result
vcr-agent-1   |     raise self._exception
vcr-agent-1   |   File "/usr/local/lib/python3.9/asyncio/selector_events.py", line 535, in _sock_connect_cb
vcr-agent-1   |     raise OSError(err, f'Connect call failed {address}')
vcr-agent-1   | ConnectionRefusedError: [Errno 111] Connect call failed ('172.19.0.10', 8080)
```

**Comment by amanji** [comment]
> @amanji how are you testing sending a W3C json credential?

We can post directly to the agent webhook topic. We don't require a didcomm connection.

**Comment by amanji** [comment]
@ianco I did modify the docker-compose configs a bit so the services might be waiting on debugpy

**Comment by ianco** [comment]
> @ianco I did modify the docker-compose configs a bit so the services might be waiting on debugpy

Should that be optional?  I just need to start all the services and post some credentials (usually thousands of them).

**Review by WadeBarnes — APPROVED** [review]

**Comment by amanji** [comment]
@ianco See PR #793 for a developer experience improvement

**Pull request merged**
