### PR TITLE
Support synonyms for credential types

### PR DESCRIPTION
**Pull request by ianco**
Signed-off-by: Ian Costanzo <ian@anon-solutions.ca>

### CODE REVIEW

**Review by swcurran — DISMISSED** [review]
Nice.  I didn't test it, but I love the idea.  Can we release?

**Comment by ianco** [comment]
> Nice. I didn't test it, but I love the idea. Can we release?

I'd like to get a review from @WadeBarnes or @esune first.  I've tested it locally but just want to make sure I haven't overlooked anything

**Comment by WadeBarnes** [comment]
@ianco, Should we also include a synonym for `relationship.registries.ca`

**Comment by ianco** [comment]
> @ianco, Should we also include a synonym for `relationship.registries.ca`

Added synonyms for relationship and also b_n (although I don't think they'll get hit, as the synonym is used for topic type, and registration is the only topic type we currently use)

**Review by WadeBarnes — APPROVED** [review]

**Comment by esune** [comment]
FYI #563 has some of the same changes as this PR, there will likely be conflicts to be resolved in order to merge that PR.

**Comment by ianco** [comment]
@esune yep I'll resolve those, I accidentally checked in 2 different updates on the same branch :-(

**Pull request merged**
