### PR TITLE
Update docs for web hook subscriptions

### PR DESCRIPTION
**Pull request by ianco**

### CODE REVIEW

**Review by alexgmetcalf — COMMENTED** [review]
Looks good, just "Acries VCR" at the top

**Review by swcurran — DISMISSED** [review]
LGTM

**Comment by swcurran** [comment]
@ianco / @amanji -- anyone know why Aries-VCR tests are failing?  Something in the setup of the tests?

**Comment by ianco** [comment]
I'm not sure but I'll look into it next week.  They've been failing for awhile.

**Comment by ianco** [comment]
> @ianco / @amanji -- anyone know why Aries-VCR tests are failing? Something in the setup of the tests?

Fixed the tests

**Review by swcurran — APPROVED** [review]
LGTM -- thanks for fixing the tests.

**Pull request merged**
